events {}

http {
    server {
        listen 8080;

        location /api/v1/auth/ { proxy_pass http://auth-service:8081; }
        location /api/v1/user/ { proxy_pass http://auth-service:8081; }
        location /api/v1/role/ { proxy_pass http://auth-service:8081; }
        location /api/v1/audit { proxy_pass http://auth-service:8081; }

        location /api/v1/students/ { proxy_pass http://academics-service:8082; }
        location /api/v1/grade/ { proxy_pass http://academics-service:8082; }
        location /api/v1/academics/ { proxy_pass http://academics-service:8082; }
        location /api/v1/exams/ { proxy_pass http://academics-service:8082; }
        location /api/v1/enter-marks { proxy_pass http://academics-service:8082; }

        location /api/v1/finance-transactions/ { proxy_pass http://finance-service:8083; }
        location /api/v1/invoicing/ { proxy_pass http://finance-service:8083; }
        location /api/v1/payments/ { proxy_pass http://finance-service:8083; }
        location /api/v1/bank { proxy_pass http://finance-service:8083; }
        location /api/v1/fee-components/ { proxy_pass http://finance-service:8083; }
        location /api/v1/register-url { proxy_pass http://finance-service:8083; }
        location /api/v1/generate-token { proxy_pass http://finance-service:8083; }
        location /api/v1/validate { proxy_pass http://finance-service:8083; }
        location /api/v1/process-call-back { proxy_pass http://finance-service:8083; }

        location /api/v1/transport/ { proxy_pass http://transport-service:8084; }
        location /api/v1/communication/ { proxy_pass http://communications-service:8086; }
        location /api/v1/reports-j { proxy_pass http://reporting-service:8087; }
         location /api/v1/analytics/ { proxy_pass http://analytics-service:8088; }

        location / {
            return 404;
        }
    }
}