version: '3.8'

services:
  backend:
    build: .
    container_name: smartedu-backend
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/bureti
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8085
      - SPRING_MAIL_USERNAME=lewiskipkemoi765@gmail.com
      - SPRING_MAIL_PASSWORD=yzvj hzze mrom gbcu
      - JWT_SECRET_KEY=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - smartedu-network

<<<<<<< HEAD
  db:
    image: mariadb:11
    container_name: edupoa-db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=bureti
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mariadb_data:
=======
networks:
  smartedu-network:
    driver: bridge
>>>>>>> 1c76a45 (all)
